### PR TITLE
Update ion-wizard.js

### PR DESCRIPTION
**Pull request by harellevy**
when routing between scope to another the next, prev, start directives should be aware to the location in the wizard.

### CODE REVIEW

**Comment by arielfaur** [comment]
Hi! I didn't really understand what your PR solves, sorry. Could you explain the problem? Thank you!

**Comment by harellevy** [comment]
lets say the wizard is in one route state which is "wizard" view, and I have another view for another "page", and i navigate between them, after starting the wizard, i'm currently in the 2nd step, the prev,next start directives should be updated when landing back on the controller of the view when returning to it,

i.e i just finished 2 step full of forms, and i'm going to my other tab, and return to the wizard view and my back button dissapear.

i hope this makes sense, if not talk to me i'll try to explain it better
You can talk to me also via skype or email
skype: harellevy
email: harellevy@gmail.com

**Comment by arielfaur** [comment]
Sorry for the delay! I am trying to imagine your use case. So in your case users can interrupt the wizard, do something else, and then come back where they left? Any chance you can create a codepen online?

**Comment by harellevy** [comment]
this is an example with the existing ion-wizard, if you're in the last step, go to another tab and return,
http://codepen.io/harellevy/pen/MaapXR?editors=101
and in this example the codepen is the same but the ion-wizard is with my code changes
http://codepen.io/harellevy/pen/Maapqd/

**Pull request merged**
